### ISSUE TITLE
code samples (gists) in 'Protect your Next.js app with security headers' are broken

### ISSUE THREAD

**Issue by samuelgoff** [RijelEk/RijelEk#1]
Hello, I read your Medium article entitled "[Protect your Next.js app with security headers](https://oslavdev.medium.com/protect-your-next-js-app-with-security-headers-7f70f4a95d63)", but unfortunately, all of the code samples (gists) are broken! As a result, I can't really read what you were trying to illustrate, and I imagine anyone else trying to read the article will be equally frustrated. I'm working on a project that uses the exact same approach (and running into a hiccup along the way), and I could really use those gists! Please update whenever you get a chance 🙏🏼

**Comment by oslavdev** [comment]
Hello, thank you very much for contacting me. I was not aware that gists
were broken. I have updated snippets.

Best,
Oslav
